version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10.2
    working_directory: ~/adjax/example
    steps:
      - checkout:
          path: ~/adjax
      - python/install-packages:
          pkg-manager: pip
          pip-dependency-file: requirements.pip
      - run:
          name: Run flake8
          command: flake8 .
      - run:
          name: Run tests
          command: ./manage.py test
